### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by philmavedzenge** [jlopez77/DeyeInverter#1]
Hi @jlopez77 , i would like to try and read my inverter's data using your program. I however have no idea where to start, what to install and where to install. Could you please help me setting it up.

**Comment by jlopez77** [comment]
Sorry but this is not an issue for the script.

1.Read the documentation
2. Install python on the computer or platform you want to run the script
3. Edit the config files and fill your data there.
4. Run the script.

If you run into issues running the script, ask.
