### ISSUE TITLE
[feature request] Modifying inverter configs

### ISSUE THREAD

**Issue by sakrlog** [jlopez77/DeyeInverter#10]
Hi, thank you for your work, I was trying to figure if there is a way to modify inverter configs/parameters via TCP calls, I tried to read through your code to see if I can help out, but I don't think i can without any leads or maybe how to start somewhere.

Thanks

**Comment by tomislavravic** [comment]
I struggled for a long time, and it’s risky writing to particular registers. What I ended up doing (recently), is buying the solar-assistant software, connected to the inverter via the cables they provide and now it’s all working peachy.

**Comment by tomislavravic** [comment]
https://solar-assistant.io/

that said, this code base by jlopez did serve me very well for almost 2 years. The clincher was the writing of settings to change the state of charge and the priority load stuff.

**Comment by vakdevi** [comment]
You may want to take a look at this project encapsulating the Solarman V5 protocol and exposing simple modbus functions - including writing of e.g. holding registers. I tested it, and it works for me.
https://github.com/jmccrohan/pysolarmanv5

**Comment by jlopez77** [comment]
I am VERY close to release an API to modify the inverter values. Stay Tuned.
