### ISSUE TITLE
Error unicodedecodeError

### ISSUE THREAD

**Issue by andreazago** [jlopez77/DeyeInverter#14]
Hi! I'am very happy to look for this version of program, bacause I have omniksol inverter with wifi module with serial 17xxxxx.
Well, when I have tryed I have this error....

Traceback (most recent call last):
  File "C:\Users\user\Desktop\HttpClient Omniksol\DeyeInverter-main\InverterData.py", line 113, in <module>
    parameters=json.loads(txtfile.read())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1035: character maps to <undefined>

I tryed to put:

with open("./DYRealTime.txt", errors="ignore")

but after I have another error....

please, may you help me ?

best regards

Andrea

**Comment by jlopez77** [comment]
I cannot test it in windows environment as I don't own any windows machine. Sorry
