### ISSUE TITLE
Deye with Serial Number 39xx

### ISSUE THREAD

**Issue by thomas-bue** [jlopez77/DeyeInverter#15]
Hey,

very nice project. I have a Deye inverter with a datalogger s/n 39xxxxxxxx.
The project itself works, but it seems the registers do not fit to the description and values.
Are you interestet into some work to update this?

If I want to update it, would it be the best to update the file DYRealTime.txt?

**Comment by jlopez77** [comment]
Hey!

In fact, the way to do it is updating the DYRealTime.txt file with the
memory positions for the 39X series.
Maybe you can call it 39DYRealtime.txt and I can do some adjustments in the
code depending on the serial number.

Best!
