### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by JoeCotty** [jlopez77/DeyeInverter#16]
Hi,
i placed your code on a Raspberry (Buster) and adapted the configfile 👍 [DeyeInverter]

inverter_ip=192.168.1.170
inverter_port=8899
inverter_sn=221111xxxx
installed_power=600
mqtt=1
mqtt_server=192.168.1.150
mqtt_port=1883
mqtt_topic=deye
mqtt_username=
mqtt_passwd=

But my seriesnumber begins with 22
When i start the script i get the following :

pi@RASPYPI3:/opt/DeyeInverter $ python3 InverterData.py
Traceback (most recent call last):
  File "InverterData.py", line 19, in <module>
    os.chdir(os.path.dirname(sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory: ''

Can you help me to get the script running.

Afterwards changing the script to get the right register values is possible for me but i need help to start the communication and get register contents

Best regards

**Comment by JoeCotty** [comment]
If i start it this way the next error occurs : 
pi@RASPYPI3:/opt/DeyeInverter $ python3 ./InverterData.py
Traceback (most recent call last):
  File "./InverterData.py", line 110, in <module>
    response=twosComplement_hex(str(''.join(hex(ord(chr(x)))[2:].zfill(2) for x in bytearray(data))+'  '+re.sub('[^\x20-\x7f]', '', ''))[p1:p2])
  File "./InverterData.py", line 14, in twosComplement_hex
    val = int(hexval, bits)
ValueError: invalid literal for int() with base 16: ''

**Comment by jlopez77** [comment]
It might have something to do with your serial number not being supported
by the script.
