### ISSUE TITLE
Inverters serial number starting with 21

### ISSUE THREAD

**Issue by tuping** [jlopez77/DeyeInverter#3]
Hello, I have 3 Deye Inverters S/N starting winth 21. I read the issues and some time ago @tomislavravic made some changes to read the parameters from this kind of inverter.
Did it work?

I am willing to help if needed.

**Comment by pepelillo** [comment]
hi all.
I'm the owner of a Deye with a 21xxxxxx S/N logger, is there any news on this?
I've seen this repo https://github.com/MichaluxPL/Sofar_LSW3 That seems to support the 21xxxxxx S/N loggers, but for Sofar inverters, Don't know it this can help.

**Comment by jlopez77** [comment]
Since I don't have an inverter with serial 21X I cannot support it. Sorry.
