### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by McAllstar** [jlopez77/DeyeInverter#8]
The instruction seem to be unclear on how to install or run this addon. I copied the file to my addon directory in home assistant and then modified the config file. when i run the run.sh command from terminal in HA I get a mqtt topic error which i don't know what to set it as. Can you maybe provide clear instructions on how to install it and set it up. thanks a mil.

**Comment by tamato27** [comment]
I will update what my procedure was once completed

**Comment by tamato27** [comment]
Make sure you have SMB enabled , then browse to your add-ons directory and clone the repo git clone https://github.com/jlopez77/DeyeInverter.git. then reboot your home assistant, once rebooted go to supervisor and install add-on solarman, Setup the config end Voilla it should be up and running, remember to add the sensors to your configuration.yaml file in home assistant first, And lastly reboot every time you make a change

**Comment by McAllstar** [comment]
Awesome, thanks a mil. Really appreciate it. Are you able to send me a sample of the config.yaml so I can see how to add the sensors and what fields are required?

From: Marius ***@***.***>
Date: Friday, 22 April 2022 at 12:19
To: jlopez77/DeyeInverter ***@***.***>
Cc: McAlister, B. (Brett) ***@***.***>, Author ***@***.***>
Subject: Re: [jlopez77/DeyeInverter] install error (Issue #8)
CAUTION - EXTERNAL SENDER - Please be careful when opening links and attachments. Nedbank - IT Information Security Department (ISD)

Make sure you have SMB enabled , then browse to your add-ons directory and clone the repo git clone https://github.com/jlopez77/DeyeInverter.git<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjlopez77%2FDeyeInverter.git&data=05%7C01%7CBrettM%40Nedbank.co.za%7C2a56d480078c473c677808da24499641%7C0b1d23d810d140938cb7fd0bb32f81e1%7C0%7C0%7C637862195746377576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mf0We2D%2BBJYhxv3mxa4Ake978R3Ucn6JmSj%2FxZi0Kxk%3D&reserved=0>. then reboot your home assistant, once rebooted go to supervisor and install add-on solarman, Setup the config end Voilla it should be up and running, remember to add the sensors to your configuration.yaml file in home assistant first, And lastly reboot every time you make a change

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjlopez77%2FDeyeInverter%2Fissues%2F8%23issuecomment-1106338935&data=05%7C01%7CBrettM%40Nedbank.co.za%7C2a56d480078c473c677808da24499641%7C0b1d23d810d140938cb7fd0bb32f81e1%7C0%7C0%7C637862195746377576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=6PiUBDXPiMFhswomuerF2k7LylGXVn4bZ6oMUKH%2FY5I%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJHBIBGVN4OS6U7ZQJZFALDVGJ4G5ANCNFSM5OOLMSXQ&data=05%7C01%7CBrettM%40Nedbank.co.za%7C2a56d480078c473c677808da24499641%7C0b1d23d810d140938cb7fd0bb32f81e1%7C0%7C0%7C637862195746377576%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iVcJ4%2FeJ%2BlluZo7VpUOUGPxljLGJfRRrr35uczdyBK0%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.***>


********************
Nedbank disclaimer and confidentiality notice:

This email may contain information that is confidential, privileged or otherwise protected from disclosure. If you are not an intended recipient of this email or all or some of the information contained therein, do not duplicate or redistribute it by any means. Please delete it and any attachments and notify the sender that you have received it in error. Unless specifically indicated, this email is neither an offer or a solicitation to buy or sell any securities, investment products or other financial product or service, nor is it an official confirmation of any transaction or an official statement of Nedbank. Any views or opinions presented are solely those of the author and do not necessarily represent those of Nedbank. Nedbank Ltd Reg No 1951/000009/06.

The following link displays the names of the Nedbank Board of Directors and Company Secretary. [http://www.nedbank.co.za/terms/DirectorsNedbank.htm]

If you do not want to click on a link, please type the relevant address in your browser
********************

**Comment by tamato27** [comment]
Well I had to modify some code to get working on my side, but if you want you can clone my repo
From what I understand about it if fix it my to be able to work, but still all cudos to @jlopez77  for sure to start this.
And so we dont spam his repo :)
